import { getValidateArray } from '../assets/validateData.js'

export const sheetData = [
  {
    name: 'Имя сервиса',
    payment_description: 'Описание проплаты при подаче в форму',
    login: 'Логин',
    email_verification: 'Почта верификации',
    last_date_payment: 'Последняя дата проплаты',
    next_date_payment: 'Следующая дата проплати',
    next_date_request: 'Следующая дата запроса фин',
    days_until_payment: 'Осталось дней до проплаты',
    days_until_request: 'Осталось дней до запроса фин',
    pay_repeat:
      'Тип оплаты (Частота повторений) Смещение проплаты в днях (1 - снятие средств на день раньше) (-1 - сняти средств на следующий день) ',
    cost: 'Сумма оплаты',
    pay: 'Оплачивается',
    is_pending: 'В ожидании оплаты',
    comments: 'Комментарии',
    id: 2,
    _sheetMeta: {
      row: 2,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Корпоративная почта',
    payment_description:
      'TG:Soul_system_admin, Department: Tech, Type: Google, Date: За 2-3 дня до снятия оплаты, Name: Корпоративная почта Google, Description: Login | Password | Email, ',
    login: 'admin@wildwildapps.com',
    email_verification: '',
    last_date_payment: '01-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '41,4 Евро',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 3,
    _sheetMeta: {
      row: 3,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Корпоративная почта',
    payment_description:
      'TG:Soul_system_admin, Department: Tech, Type: Google, Date: За 2-3 дня до снятия оплаты, Name: Корпоративная почта Google, Description: Login | Password | Email, ',
    login: 'ivan@wildwild.partners',
    email_verification: '',
    last_date_payment: '01-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '49,68 Евро',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 4,
    _sheetMeta: {
      row: 4,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Окто WWL',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildtech.tech@gmail.com',
    email_verification: '',
    last_date_payment: '27-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждые 30 дней',
    cost: '329 Евро',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 5,
    _sheetMeta: {
      row: 5,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Окто WWA',
    payment_description:
      'TG:Soul_system_admin, Department: WWA, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWA, Description: Email | Password, ',
    login: 'webking.com.ua@gmail.com',
    email_verification: '',
    last_date_payment: '24-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждые 30 дней',
    cost: '429 Евро',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 6,
    _sheetMeta: {
      row: 6,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'ChatGPT IT RnD',
    payment_description:
      'TG:Soul_system_admin, Department: IT RnD, Type: Chat Gpt, Date: За 2-3 дня до снятия оплаты, Name: ChatGPT IT RnD, Description: Email | Password , ',
    login: 'wwildleads.devop@gmail.com',
    email_verification: 'wwildleads.devop@gmail.com',
    last_date_payment: '17-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '24 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 7,
    _sheetMeta: {
      row: 7,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'ChatGPT Buyers',
    payment_description:
      'TG:Soul_system_admin, Department: Buyers, Type: Chat Gpt, Date: За 2-3 дня до снятия оплаты, Name: ChatGPT Buyers, Description: Email | Password , ',
    login: 'wwbckptech@gmail.com',
    email_verification: 'wwbckptech@gmail.com',
    last_date_payment: '22-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '24 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 8,
    _sheetMeta: {
      row: 8,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'ChatGPT Supports',
    payment_description:
      'TG:Soul_system_admin, Department: Supports, Type: Chat Gpt, Date: За 2-3 дня до снятия оплаты, Name: ChatGPT Supports, Description: Email | Password , ',
    login: 'supp.wwa@gmail.com',
    email_verification: 'supp.wwa@gmail.com',
    last_date_payment: '19-02-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '24 Долларов',
    pay: 'FALSE',
    is_pending: null,
    comments: null,
    id: 9,
    _sheetMeta: {
      row: 9,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'ChatGPT Android',
    payment_description:
      'TG:Soul_system_admin, Department: Android, Type: Chat Gpt, Date: За 2-3 дня до снятия оплаты, Name: ChatGPT Android, Description: Email | Password , ',
    login: 'wwildtech.sys@gmail.com',
    email_verification: 'wwildtech.sys@gmail.com',
    last_date_payment: '24-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '24 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 10,
    _sheetMeta: {
      row: 10,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'ChatGPT IOS',
    payment_description:
      'TG:Soul_system_admin, Department: IOS, Type: Chat Gpt, Date: За 2-3 дня до снятия оплаты, Name: Namechep, Description: Email | Password , ',
    login: 'wwildleads.cheap@gmail.com',
    email_verification: 'wwildleads.cheap@gmail.com',
    last_date_payment: '24-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '24 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 11,
    _sheetMeta: {
      row: 11,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Namechep',
    payment_description:
      'TG:Soul_system_admin, Department: Tech, Type: Domains Date: За 2-3 дня до снятия оплаты, Name: Namechep, Description: Email | Password , ',
    login: 'arbitraffic',
    email_verification: 'wwildtech.tech@gmail.com',
    last_date_payment: '',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'По запросу',
    cost: '0 Долларов',
    pay: null,
    is_pending: null,
    comments: null,
    id: 12,
    _sheetMeta: {
      row: 12,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Namechep',
    payment_description:
      'TG:Soul_system_admin, Department: Tech, Type: Domains, Date: За 2-3 дня до снятия оплаты, Name: Namechep, Description: Email | Password , ',
    login: 'travianz',
    email_verification: 'wwildleads.cheap@gmail.com',
    last_date_payment: '',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'По запросу',
    cost: '0 Долларов',
    pay: '',
    is_pending: '',
    comments: '',
    id: 13,
    _sheetMeta: {
      row: 13,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Namechep',
    payment_description:
      'TG:Soul_system_admin, Department: Tech, Type: Domains, Date: За 2-3 дня до снятия оплаты, Name: Namechep, Description: Email | Password , ',
    login: 'OleksiiSystem',
    email_verification: 'bazaspace32@gmail.com',
    last_date_payment: '',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'По запросу',
    cost: '0 Долларов',
    pay: null,
    is_pending: null,
    comments: null,
    id: 14,
    _sheetMeta: {
      row: 14,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Namechep',
    payment_description:
      'TG:Soul_system_admin, Department: Tech, Type: Domains, Date: За 2-3 дня до снятия оплаты, Name: Namechep, Description: Email | Password , ',
    login: 'starchartni',
    email_verification: 'wwildtech.sys@gmail.com ',
    last_date_payment: '',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'По запросу',
    cost: '0 Долларов',
    pay: null,
    is_pending: null,
    comments: null,
    id: 15,
    _sheetMeta: {
      row: 15,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: null,
    payment_description: null,
    login: null,
    email_verification: null,
    last_date_payment: null,
    next_date_payment: null,
    next_date_request: null,
    days_until_payment: null,
    days_until_request: null,
    pay_repeat: null,
    cost: null,
    pay: null,
    is_pending: null,
    comments: null,
    id: 16,
    _sheetMeta: {
      row: 16,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Покупка / отправка девайсов',
    payment_description: '',
    login: '',
    email_verification: '',
    last_date_payment: '',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'По запросу',
    cost: null,
    pay: null,
    is_pending: null,
    comments: null,
    id: 17,
    _sheetMeta: {
      row: 17,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: null,
    payment_description: null,
    login: null,
    email_verification: null,
    last_date_payment: null,
    next_date_payment: null,
    next_date_request: null,
    days_until_payment: null,
    days_until_request: null,
    pay_repeat: null,
    cost: null,
    pay: null,
    is_pending: null,
    comments: null,
    id: 18,
    _sheetMeta: {
      row: 18,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Покупка / продление срока годности сим',
    payment_description: '',
    login: '',
    email_verification: '',
    last_date_payment: '',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'По запросу',
    cost: null,
    pay: null,
    is_pending: null,
    comments: null,
    id: 19,
    _sheetMeta: {
      row: 19,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: null,
    payment_description: null,
    login: null,
    email_verification: null,
    last_date_payment: null,
    next_date_payment: null,
    next_date_request: null,
    days_until_payment: null,
    days_until_request: null,
    pay_repeat: null,
    cost: null,
    pay: null,
    is_pending: null,
    comments: null,
    id: 20,
    _sheetMeta: {
      row: 20,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '29-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 21,
    _sheetMeta: {
      row: 21,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый месяц -1)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '29-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц -1 день',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 22,
    _sheetMeta: {
      row: 22,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый месяц +1)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '24-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц +1 день',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 23,
    _sheetMeta: {
      row: 23,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый месяц -2)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '29-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц -2 дня',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 24,
    _sheetMeta: {
      row: 24,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый месяц +2)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '24-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц +2 дня',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 25,
    _sheetMeta: {
      row: 25,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый год)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '18-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый год',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 26,
    _sheetMeta: {
      row: 26,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый год -1)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '18-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый год -1 день',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 27,
    _sheetMeta: {
      row: 27,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый год +1)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '09-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый год +1 день',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 28,
    _sheetMeta: {
      row: 28,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый год -2)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '18-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый год -2 дня',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 29,
    _sheetMeta: {
      row: 29,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Asana (Каждый год +2)',
    payment_description:
      'TG:Soul_system_admin, Department: WWL, Type: Octo, Date: За 2-3 дня до снятия оплаты, Name: Окто WWL, Description: Email | Password, ',
    login: 'wwildleads@gmail.com ',
    email_verification: '',
    last_date_payment: '09-01-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый год +2 дня',
    cost: '1080 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 30,
    _sheetMeta: {
      row: 30,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Amazon',
    payment_description: '',
    login: 'wwildleads@gmail.com',
    email_verification: '',
    last_date_payment: '01-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '3540 usd +355 usd',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 31,
    _sheetMeta: {
      row: 31,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Members api',
    payment_description: '',
    login: 'wwildtech.tech@gmail.com',
    email_verification: '',
    last_date_payment: '01-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '15 евро',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 32,
    _sheetMeta: {
      row: 32,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'https://app.tyver.io/',
    payment_description: '',
    login: 'wwildtech.tech@gmail.com',
    email_verification: '',
    last_date_payment: '03-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '75 usd',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 33,
    _sheetMeta: {
      row: 33,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Кейтаро newtraffnewlife.com',
    payment_description: '',
    login: '',
    email_verification: '',
    last_date_payment: '01-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '249 Евро',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 34,
    _sheetMeta: {
      row: 34,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'VPN Proton (Supports | QA)',
    payment_description: '',
    login: 'supp.wwa@gmail.com',
    email_verification: '',
    last_date_payment: '13-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '9.9 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 35,
    _sheetMeta: {
      row: 35,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'VPN Cyber ghost',
    payment_description: '',
    login: 'wwildleads@gmail.com',
    email_verification: '',
    last_date_payment: '08-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '14.27 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 36,
    _sheetMeta: {
      row: 36,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'VPN surfshark',
    payment_description: '',
    login: 'tech.ivan.wwl@gmail.com',
    email_verification: '',
    last_date_payment: '28-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '23 Доллара',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 37,
    _sheetMeta: {
      row: 37,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Termius 1',
    payment_description: '',
    login: 'arbi.traffic.pb@gmail.com',
    email_verification: '',
    last_date_payment: '09-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '72 usd',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 38,
    _sheetMeta: {
      row: 38,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Termius 2',
    payment_description: '',
    login: 'arbi.traffic.pb@gmail.com',
    email_verification: '',
    last_date_payment: '12-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '95 usd',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 39,
    _sheetMeta: {
      row: 39,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'Qase',
    payment_description: '',
    login: 'wwildtech.tech@gmail.com',
    email_verification: '',
    last_date_payment: '13-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '150 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 40,
    _sheetMeta: {
      row: 40,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'cloudflare',
    payment_description: '',
    login: 'wwildtech.tech@gmail.com',
    email_verification: '',
    last_date_payment: '22-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '210 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 41,
    _sheetMeta: {
      row: 41,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'web flow 1',
    payment_description: '',
    login: 'wwateam2022@gmail.com',
    email_verification: '',
    last_date_payment: '14-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '18 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 42,
    _sheetMeta: {
      row: 42,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
  {
    name: 'web flow 1',
    payment_description: '',
    login: 'wwateam2022@gmail.com',
    email_verification: '',
    last_date_payment: '22-03-2025',
    next_date_payment: '',
    next_date_request: '',
    days_until_payment: '',
    days_until_request: '',
    pay_repeat: 'Каждый месяц',
    cost: '28 Долларов',
    pay: 'TRUE',
    is_pending: null,
    comments: null,
    id: 43,
    _sheetMeta: {
      row: 43,
      cols: {
        name: 'A',
        payment_description: 'B',
        login: 'C',
        email_verification: 'D',
        last_date_payment: 'E',
        next_date_payment: 'F',
        next_date_request: 'G',
        days_until_payment: 'H',
        days_until_request: 'I',
        pay_repeat: 'J',
        cost: 'K',
        pay: 'L',
        is_pending: 'M',
        comments: 'N',
      },
    },
  },
]

export const getSheetData = () => {
  return sheetData
}

export const setSheetData = (newData) => {
  const newDataArray = getValidateArray(newData)
  sheetData.splice(0, sheetData.length, ...newDataArray)
}
